package fr.pivot.pilotage.profile;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import fr.pivot.pilotage.schedule.projection.Altitude;

/**
 * JPA entity for a tenant's <strong>optional</strong> organization-profile override (EN18.10,
 * frozen contract §c) — table {@code pilotage.organization_profile}.
 *
 * <p>Exactly <strong>one profile per tenant</strong> is allowed ({@code tenant_id} carries a
 * {@code UNIQUE} constraint and a FK to {@code public.tenants(id)}). A row present here overrides
 * the versioned default ({@link DefaultProfileProperties}) for that tenant; absent, the resolver
 * falls back to the versioned default without ever writing a row. The resolver never reads another
 * tenant's row (cross-tenant isolation).
 *
 * <p>{@code default_modules} is stored as JSONB and mapped via {@link SqlTypes#JSON} — the entity
 * holds the raw JSON array string; {@link OrganizationProfileResolver} parses it into a
 * {@code Set<String>}. This entity is never exposed directly in the API (CLAUDE.md §Standards) —
 * the resolver returns the immutable {@link DefaultOrganizationProfile} record.
 */
@Entity
@Table(name = "organization_profile", schema = "pilotage")
public class OrganizationProfile {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this profile; unique (one profile per tenant), FK to public.tenants(id). */
    @Column(name = "tenant_id", nullable = false, unique = true)
    private Long tenantId;

    /** Overridden view altitude / render cursor. */
    @Enumerated(EnumType.STRING)
    @Column(name = "altitude", nullable = false, length = 16)
    private Altitude altitude;

    /** Overridden sovereignty class. */
    @Enumerated(EnumType.STRING)
    @Column(name = "sovereignty_class", nullable = false, length = 16)
    private SovereigntyClass sovereigntyClass;

    /** Overridden rigor level. */
    @Enumerated(EnumType.STRING)
    @Column(name = "rigor_level", nullable = false, length = 16)
    private RigorLevel rigorLevel;

    /** Overridden default module ids, stored as a JSONB array string. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "default_modules", columnDefinition = "jsonb", nullable = false)
    private String defaultModules;

    /** Timestamp when the profile was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected OrganizationProfile() {
    }

    /**
     * Full constructor for creating a tenant profile override.
     *
     * @param tenantId         owning tenant's {@code public.tenants.id}
     * @param altitude         overridden view altitude
     * @param sovereigntyClass overridden sovereignty class
     * @param rigorLevel       overridden rigor level
     * @param defaultModules   overridden module ids as a JSON array string
     */
    public OrganizationProfile(final Long tenantId, final Altitude altitude,
            final SovereigntyClass sovereigntyClass, final RigorLevel rigorLevel,
            final String defaultModules) {
        this.tenantId = tenantId;
        this.altitude = altitude;
        this.sovereigntyClass = sovereigntyClass;
        this.rigorLevel = rigorLevel;
        this.defaultModules = defaultModules;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the profile identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the overridden view altitude.
     *
     * @return the {@link Altitude}
     */
    public Altitude getAltitude() {
        return altitude;
    }

    /**
     * Sets the overridden view altitude.
     *
     * @param altitude the altitude to set
     */
    public void setAltitude(final Altitude altitude) {
        this.altitude = altitude;
    }

    /**
     * Returns the overridden sovereignty class.
     *
     * @return the {@link SovereigntyClass}
     */
    public SovereigntyClass getSovereigntyClass() {
        return sovereigntyClass;
    }

    /**
     * Sets the overridden sovereignty class.
     *
     * @param sovereigntyClass the sovereignty class to set
     */
    public void setSovereigntyClass(final SovereigntyClass sovereigntyClass) {
        this.sovereigntyClass = sovereigntyClass;
    }

    /**
     * Returns the overridden rigor level.
     *
     * @return the {@link RigorLevel}
     */
    public RigorLevel getRigorLevel() {
        return rigorLevel;
    }

    /**
     * Sets the overridden rigor level.
     *
     * @param rigorLevel the rigor level to set
     */
    public void setRigorLevel(final RigorLevel rigorLevel) {
        this.rigorLevel = rigorLevel;
    }

    /**
     * Returns the overridden module ids as a JSON array string.
     *
     * @return the JSON array string of module ids
     */
    public String getDefaultModules() {
        return defaultModules;
    }

    /**
     * Sets the overridden module ids as a JSON array string.
     *
     * @param defaultModules the JSON array string to set
     */
    public void setDefaultModules(final String defaultModules) {
        this.defaultModules = defaultModules;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
