package fr.pivot.pilotage.roadmap;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity representing a {@code lane} (US22.3.1) — a flat, horizontal grouping of the roadmap
 * "rapide" macro view: a theme, a team or an objective, at the user's discretion.
 *
 * <p><strong>Concept introduced by this US</strong> (the backlog Gate 1 file left the technical
 * design open — see {@code pivot-docs/docs/backlog/EPIC-roadmap/FEATURES/roadmap-rapide/
 * us-creer-roadmap-rapide.md}, section "Notes d'implémentation", for the full contract). A lane
 * carries no fixed taxonomy: {@link #name} is a free-form label, never an enum/"kind" column — the
 * US explicitly asks to stay minimal (no complex hierarchy).
 *
 * <p><strong>Distinct from {@code fr.pivot.pilotage.schedule.Phase}</strong>: a phase is a
 * time/WBS macro-grouping optionally backed by a root summary task (EN22.1a); a lane is an axis
 * <em>orthogonal</em> to time, never adossed to a task. Both concepts coexist without
 * substituting one another.
 *
 * <p>An "initiative" posed on a lane is <strong>not</strong> a new entity — per the backlog note
 * ("the initiative created here is a macro view laid over the same temporal graph as the Gantt
 * (EN22.1) — no separate entity, no double entry"), it is a plain
 * {@code fr.pivot.pilotage.schedule.Task} (leaf, shared in the roadmap) whose
 * {@code lane_id} column points back at this entity.
 *
 * <p>Belongs to a single tenant ({@code public.tenants.id}), a single team
 * ({@code public.teams.id}) and exactly one {@code pilotage.project}. Timestamps are managed
 * automatically via JPA lifecycle callbacks.
 */
@Entity
@Table(name = "lane", schema = "pilotage")
public class Lane {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this lane; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team that owns this lane; used for per-team portfolio scoping. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Owning project id (FK {@code pilotage.project(id)}). */
    @Column(name = "project_id", nullable = false)
    private Long projectId;

    /** Human-readable lane label (theme / team / objective); maximum 255 characters. */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /** Display order of the lane within its project. */
    @Column(name = "position", nullable = false)
    private Integer position;

    /** Timestamp when the lane was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected Lane() {
    }

    /**
     * Full constructor for creating a new lane.
     *
     * @param tenantId  owning tenant's {@code public.tenants.id}
     * @param teamId    owning team's {@code public.teams.id}
     * @param projectId owning project id
     * @param name      lane label (max 255 chars)
     * @param position  display order within the project
     */
    public Lane(final Long tenantId, final Long teamId, final Long projectId, final String name,
            final Integer position) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.projectId = projectId;
        this.name = name;
        this.position = position;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the lane identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the owning team id.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the owning project id.
     *
     * @return the project id
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * Returns the lane label.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the lane label.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the display position.
     *
     * @return the position
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * Sets the display position.
     *
     * @param position the position to set
     */
    public void setPosition(final Integer position) {
        this.position = position;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
