package fr.pivot.pilotage.roadmap;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity representing a read-only roadmap share link (US22.3.5).
 *
 * <p><strong>Replicates the {@code pivot-core} {@code fr.pivot.auth.entity.AccessToken}
 * pattern</strong> (CLAUDE.md instruction — "même discipline que les tokens d'accès ailleurs sur
 * la plateforme"): the raw token (256 bits of {@link java.security.SecureRandom}, hex-encoded to
 * 64 chars, generated by {@link RoadmapShareService}) is <strong>never persisted</strong> — only
 * its SHA-256 hex-encoded hash ({@link #tokenHash}). Unlike {@code AccessToken}, there is no
 * {@code status} enum: liveness is a pure function of two independent, nullable timestamps —
 * {@link #revokedAt} (manual revocation) and {@link #expiresAt} (optional programmed expiry) —
 * see {@link #isActive()}.
 *
 * <p>Strictly scoped to one project ({@link #projectId}, {@code NOT NULL}, {@code ON DELETE
 * CASCADE} at the schema level) — the security AC ("le lien ne doit exposer que les données de la
 * roadmap concernée") is enforced from the schema up: a share link can never point at a
 * portfolio, a tenant, or "everything visible to a user".
 *
 * <p>No {@code updatedAt} column, deliberately — a share link is never "edited" in the business
 * sense, only revoked (a one-way, one-time event captured by {@link #revokedAt}), mirroring
 * {@code AccessToken} (which also has no {@code updatedAt}).
 */
@Entity
@Table(name = "roadmap_share_link", schema = "pilotage")
public class RoadmapShareLink {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this share link's project; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team that owns this share link's project; used for per-team portfolio scoping. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** The single project this link grants read-only access to. */
    @Column(name = "project_id", nullable = false)
    private Long projectId;

    /** SHA-256 hex-encoded hash of the raw token — the raw value is never persisted. */
    @Column(name = "token_hash", nullable = false, unique = true, length = 64)
    private String tokenHash;

    /** Timestamp when the link was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp when the link was revoked by an authorized user, or {@code null} if still live. */
    @Column(name = "revoked_at")
    private Instant revokedAt;

    /** Optional absolute expiry timestamp, or {@code null} for no programmed expiry. */
    @Column(name = "expires_at")
    private Instant expiresAt;

    /** No-arg constructor required by JPA. */
    protected RoadmapShareLink() {
    }

    /**
     * Full constructor for creating a new share link.
     *
     * @param tenantId  owning tenant's {@code public.tenants.id}
     * @param teamId    owning team's {@code public.teams.id}
     * @param projectId the single project this link grants read-only access to
     * @param tokenHash SHA-256 hex-encoded hash of the raw token (never the raw token itself)
     * @param expiresAt optional absolute expiry timestamp, or {@code null} for none
     */
    public RoadmapShareLink(final Long tenantId, final Long teamId, final Long projectId, final String tokenHash,
            final Instant expiresAt) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.projectId = projectId;
        this.tokenHash = tokenHash;
        this.expiresAt = expiresAt;
    }

    /** Sets {@code createdAt} to the current instant before the first insert, when unset. */
    @PrePersist
    public void prePersist() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now();
        }
    }

    /**
     * Returns whether this link currently grants read-only access.
     *
     * @return {@code true} if not revoked and (no expiry set, or expiry is still in the future)
     */
    public boolean isActive() {
        return revokedAt == null && (expiresAt == null || expiresAt.isAfter(Instant.now()));
    }

    /**
     * Returns the share link identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the owning team id.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the project this link grants read-only access to.
     *
     * @return the project id
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * Returns the SHA-256 hash of the raw token.
     *
     * @return 64-char lowercase hex string
     */
    public String getTokenHash() {
        return tokenHash;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the revocation timestamp.
     *
     * @return the revokedAt instant, or {@code null} if never revoked
     */
    public Instant getRevokedAt() {
        return revokedAt;
    }

    /**
     * Sets the revocation timestamp.
     *
     * @param revokedAt the revocation instant to set
     */
    public void setRevokedAt(final Instant revokedAt) {
        this.revokedAt = revokedAt;
    }

    /**
     * Returns the optional expiry timestamp.
     *
     * @return the expiresAt instant, or {@code null} if no expiry is programmed
     */
    public Instant getExpiresAt() {
        return expiresAt;
    }
}
