sonar.projectKey=PIVOT-PLATFORM_pivot-pilotage-core
sonar.organization=pivot-platform
sonar.projectName=pivot-pilotage-core

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.source=24

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/generated/**,src/main/resources/**
sonar.test.exclusions=target/**

sonar.sourceEncoding=UTF-8
