package fr.pivot.pilotage.baseline;

import fr.pivot.pilotage.schedule.TemporalPrecision;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * JPA entity representing a {@code baseline_snapshot} (EN22.1a, frozen contract §a) — the per-task
 * frozen values of a {@link Baseline}.
 *
 * <p>Carries frozen start/finish, duration, work, cost and the frozen altitude
 * ({@code bl_temporal_precision}) — the latter lets a fuzzy roadmap baseline be compared to a
 * precise Gantt actual. Belongs to a single tenant ({@code public.tenants.id}).
 */
@Entity
@Table(name = "baseline_snapshot", schema = "pilotage")
public class BaselineSnapshot {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this snapshot; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Owning baseline id (FK {@code pilotage.baseline(id)}). */
    @Column(name = "baseline_id", nullable = false)
    private Long baselineId;

    /** Task id (FK {@code pilotage.task(id)}). */
    @Column(name = "task_id", nullable = false)
    private Long taskId;

    /** Frozen start date; may be {@code null}. */
    @Column(name = "bl_start")
    private Instant blStart;

    /** Frozen finish date; may be {@code null}. */
    @Column(name = "bl_finish")
    private Instant blFinish;

    /** Frozen duration in minutes; may be {@code null}. */
    @Column(name = "bl_duration_minutes")
    private Integer blDurationMinutes;

    /** Frozen work in minutes; may be {@code null}. */
    @Column(name = "bl_work_minutes")
    private Integer blWorkMinutes;

    /** Frozen cost amount; may be {@code null}. */
    @Column(name = "bl_cost_amount", precision = 18, scale = 4)
    private BigDecimal blCostAmount;

    /** Frozen altitude; may be {@code null}. */
    @Enumerated(EnumType.STRING)
    @Column(name = "bl_temporal_precision", length = 16)
    private TemporalPrecision blTemporalPrecision;

    /** Timestamp when the snapshot was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected BaselineSnapshot() {
    }

    /**
     * Minimal constructor for creating a new baseline snapshot.
     *
     * @param tenantId    owning tenant's {@code public.tenants.id}
     * @param baselineId  owning baseline id
     * @param taskId      the task id
     */
    public BaselineSnapshot(final Long tenantId, final Long baselineId, final Long taskId) {
        this.tenantId = tenantId;
        this.baselineId = baselineId;
        this.taskId = taskId;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the snapshot identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the owning baseline id.
     *
     * @return the baseline id
     */
    public Long getBaselineId() {
        return baselineId;
    }

    /**
     * Returns the task id.
     *
     * @return the task id
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * Returns the frozen start date.
     *
     * @return the frozen start, or {@code null}
     */
    public Instant getBlStart() {
        return blStart;
    }

    /**
     * Sets the frozen start date.
     *
     * @param blStart the frozen start (may be {@code null})
     */
    public void setBlStart(final Instant blStart) {
        this.blStart = blStart;
    }

    /**
     * Returns the frozen finish date.
     *
     * @return the frozen finish, or {@code null}
     */
    public Instant getBlFinish() {
        return blFinish;
    }

    /**
     * Sets the frozen finish date.
     *
     * @param blFinish the frozen finish (may be {@code null})
     */
    public void setBlFinish(final Instant blFinish) {
        this.blFinish = blFinish;
    }

    /**
     * Returns the frozen duration in minutes.
     *
     * @return the frozen duration, or {@code null}
     */
    public Integer getBlDurationMinutes() {
        return blDurationMinutes;
    }

    /**
     * Sets the frozen duration in minutes.
     *
     * @param blDurationMinutes the frozen duration (may be {@code null})
     */
    public void setBlDurationMinutes(final Integer blDurationMinutes) {
        this.blDurationMinutes = blDurationMinutes;
    }

    /**
     * Returns the frozen work in minutes.
     *
     * @return the frozen work, or {@code null}
     */
    public Integer getBlWorkMinutes() {
        return blWorkMinutes;
    }

    /**
     * Sets the frozen work in minutes.
     *
     * @param blWorkMinutes the frozen work (may be {@code null})
     */
    public void setBlWorkMinutes(final Integer blWorkMinutes) {
        this.blWorkMinutes = blWorkMinutes;
    }

    /**
     * Returns the frozen cost amount.
     *
     * @return the frozen cost, or {@code null}
     */
    public BigDecimal getBlCostAmount() {
        return blCostAmount;
    }

    /**
     * Sets the frozen cost amount.
     *
     * @param blCostAmount the frozen cost (may be {@code null})
     */
    public void setBlCostAmount(final BigDecimal blCostAmount) {
        this.blCostAmount = blCostAmount;
    }

    /**
     * Returns the frozen altitude.
     *
     * @return the frozen {@link TemporalPrecision}, or {@code null}
     */
    public TemporalPrecision getBlTemporalPrecision() {
        return blTemporalPrecision;
    }

    /**
     * Sets the frozen altitude.
     *
     * @param blTemporalPrecision the frozen precision (may be {@code null})
     */
    public void setBlTemporalPrecision(final TemporalPrecision blTemporalPrecision) {
        this.blTemporalPrecision = blTemporalPrecision;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
