package fr.pivot.pilotage.baseline;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity representing a {@code baseline} (EN22.1a, frozen contract §a) — one of 0..10 frozen
 * plans captured for a project.
 *
 * <p>Schema-level constraints: {@code UNIQUE(project_id, baseline_index)} and
 * {@code CHECK baseline_index BETWEEN 0 AND 10}. Per-task frozen values live in
 * {@link BaselineSnapshot}. Belongs to a single tenant ({@code public.tenants.id}).
 */
@Entity
@Table(name = "baseline", schema = "pilotage")
public class Baseline {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this baseline; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team that owns this baseline; used for per-team portfolio scoping. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Owning project id (FK {@code pilotage.project(id)}). */
    @Column(name = "project_id", nullable = false)
    private Long projectId;

    /** Baseline index in the range 0..10, unique per project. */
    @Column(name = "baseline_index", nullable = false)
    private Short baselineIndex;

    /** When the baseline was captured. */
    @Column(name = "captured_at", nullable = false)
    private Instant capturedAt;

    /** Timestamp when the baseline was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected Baseline() {
    }

    /**
     * Full constructor for creating a new baseline.
     *
     * @param tenantId      owning tenant's {@code public.tenants.id}
     * @param teamId        owning team's {@code public.teams.id}
     * @param projectId     owning project id
     * @param baselineIndex baseline index in 0..10
     * @param capturedAt    capture timestamp
     */
    public Baseline(final Long tenantId, final Long teamId, final Long projectId, final Short baselineIndex,
            final Instant capturedAt) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.projectId = projectId;
        this.baselineIndex = baselineIndex;
        this.capturedAt = capturedAt;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the baseline identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the owning project id.
     *
     * @return the project id
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * Returns the baseline index.
     *
     * @return the baseline index (0..10)
     */
    public Short getBaselineIndex() {
        return baselineIndex;
    }

    /**
     * Returns the capture timestamp.
     *
     * @return the captured-at instant
     */
    public Instant getCapturedAt() {
        return capturedAt;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
