package fr.pivot.pilotage.dashboard;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * JPA entity representing one user's personalized dashboard (US23.2.2) — the widget layout
 * persisted "par utilisateur dans le schéma pilotage" (Notes d'implémentation).
 *
 * <p><strong>{@code userId}: no FK.</strong> {@code pivot-pilotage-core/CLAUDE.md} restricts
 * cross-schema FK to <em>only</em> {@code public.tenants.id}/{@code public.teams.id}, never
 * {@code public.users.id} — the identity table stays exclusively {@code pivot-core}'s, consumed
 * without a foreign key today, exactly the "logical reference" precedent already used by
 * {@code pilotage.assignment.resource_ref} (a resource identity resolved elsewhere, never joined
 * to). {@code userId} is a plain, unvalidated {@code BIGINT}, gap-era stand-in for the caller's own
 * id (see {@link DashboardController} for the full path-variable rationale).
 *
 * <p><strong>{@code teamId} is a genuine resolution dimension here</strong> — {@code UNIQUE
 * (tenant_id, team_id, user_id)}, unlike {@code pilotage.organization_profile}'s {@code UNIQUE
 * (tenant_id)} (that table's team_id is attribution-only, by explicit historical/frozen-contract
 * necessity documented in {@code V1__schema_init.sql}). This is a brand-new table with no such
 * legacy constraint, so it follows the dominant repo convention instead (every other
 * {@code pilotage.*} table scopes by tenant <em>and</em> team) — a user may have one dashboard per
 * team they operate in.
 *
 * <p><strong>{@code profile} is a free label, not an enum.</strong> AC1 ("Given un profil et un
 * layout personnalisé persisté...") reads the profile as an <em>external</em> input (the caller's
 * persona/role, ultimately sourced from {@code TenantContext} once {@code pivot-core-starter} is
 * consumable — CLAUDE.md §gap) — this module does not own or invent a closed taxonomy of profiles
 * (frontmatter: "Profils: Tous"). It is persisted purely as an informational echo of who the layout
 * was tailored for, exactly like {@code pilotage.lane.name}'s "aucune taxonomie figée" precedent.
 * Actual rendering behavior is fully driven by {@link #viewMode} and the widget list, never by
 * this field.
 *
 * <p>{@code ddl-auto: none} (Flyway owns the schema, cf. {@code application.yml}) — the real
 * {@code UNIQUE (tenant_id, team_id, user_id)} constraint lives in {@code V1__schema_init.sql}
 * ({@code uq_dashboard_config_tenant_team_user}), not duplicated here as a JPA
 * {@code @Table(uniqueConstraints=...)} (mirrors {@code fr.pivot.pilotage.roadmap.Lane}, which
 * likewise leaves its own DB-level unique constraint undeclared at the JPA level).
 */
@Entity
@Table(name = "dashboard_config", schema = "pilotage")
public class DashboardConfig {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this dashboard; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team the dashboard was configured under; a genuine resolution dimension (see class doc). */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Owning user's id — no FK (see class doc), gap-era stand-in for the caller's own identity. */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    /** Free, caller-supplied persona label (see class doc) — never a closed taxonomy. */
    @Column(name = "profile", nullable = false, length = 64)
    private String profile;

    /** Rendering mode chosen by the user for this dashboard. */
    @Enumerated(EnumType.STRING)
    @Column(name = "view_mode", nullable = false, length = 16)
    private DashboardViewMode viewMode;

    /**
     * Configured widgets (bidirectional {@code @OneToMany}), ordered by {@code position}.
     *
     * <p>Mapped by {@link DashboardWidget#getDashboardConfig()}; cascades persistence and orphan
     * removal so a full-replace save ({@link #replaceWidgets}) stays consistent with the
     * database-level {@code ON DELETE CASCADE} on {@code pilotage.dashboard_widget.dashboard_config_id}.
     */
    @OneToMany(mappedBy = "dashboardConfig", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("position ASC")
    private List<DashboardWidget> widgets = new ArrayList<>();

    /** Timestamp when the dashboard was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected DashboardConfig() {
    }

    /**
     * Full constructor for creating a new dashboard.
     *
     * @param tenantId owning tenant's {@code public.tenants.id}
     * @param teamId   the team this dashboard was configured under
     * @param userId   the owning user's id (no FK, see class doc)
     * @param profile  the caller-supplied persona label
     * @param viewMode the chosen rendering mode
     */
    public DashboardConfig(final Long tenantId, final Long teamId, final Long userId, final String profile,
            final DashboardViewMode viewMode) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.userId = userId;
        this.profile = profile;
        this.viewMode = viewMode;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before the first
     * insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} to the current instant before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Replaces this dashboard's profile, view mode and full widget list in one call (US23.2.2 AC3
     * — "modification du layout... persistée"). A full replace, never a partial merge: the caller
     * (service layer) is expected to have already validated the whole incoming layout before this
     * is invoked, so no partial state is ever left orphaned.
     *
     * @param newProfile  the new persona label
     * @param newViewMode the new rendering mode
     * @param newWidgets  the complete new widget list, in the order they should render; each is
     *                    re-parented to this dashboard
     */
    public void replaceWidgets(final String newProfile, final DashboardViewMode newViewMode,
            final List<DashboardWidget> newWidgets) {
        this.profile = newProfile;
        this.viewMode = newViewMode;
        this.widgets.clear();
        for (final DashboardWidget widget : newWidgets) {
            this.widgets.add(widget);
            widget.setDashboardConfig(this);
        }
    }

    /**
     * Returns the dashboard's unique identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the owning user's id.
     *
     * @return the user id (no FK, see class doc)
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Returns the caller-supplied persona label.
     *
     * @return the profile label
     */
    public String getProfile() {
        return profile;
    }

    /**
     * Returns the rendering mode.
     *
     * @return the {@link DashboardViewMode}
     */
    public DashboardViewMode getViewMode() {
        return viewMode;
    }

    /**
     * Returns an unmodifiable, position-ordered view of this dashboard's widgets.
     *
     * @return an unmodifiable list of widgets
     */
    public List<DashboardWidget> getWidgets() {
        return Collections.unmodifiableList(widgets);
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
