package fr.pivot.pilotage.dashboard;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity representing one widget on a {@link DashboardConfig} (US23.2.2). Every widget is
 * currently application-scoped ({@link #applicationId} {@code NOT NULL}, see
 * {@link DashboardWidgetType} class doc) and carries a grid disposition
 * ({@code gridRow}/{@code gridColumn}/{@code gridWidth}/{@code gridHeight}) validated against a
 * 4-column grid by {@link DashboardService} before persistence (AC error: "disposition hors
 * bornes") — the DB {@code CHECK} constraints in {@code V1__schema_init.sql} are defense-in-depth,
 * not the primary validation path (mirrors {@code pilotage.task_dependency}'s acyclicity check:
 * the invariant that needs a caller-facing message is enforced in the service, never relied upon
 * to surface cleanly from a raw SQL constraint violation).
 *
 * <p>{@code tenantId}/{@code teamId} are duplicated on the widget (rather than only reachable
 * through {@link #dashboardConfig}) — same "direct filtering without a systematic join" rationale
 * used by every other {@code pilotage.*} child table.
 */
@Entity
@Table(name = "dashboard_widget", schema = "pilotage")
public class DashboardWidget {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The dashboard this widget belongs to; never {@code null} once persisted. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "dashboard_config_id", nullable = false)
    private DashboardConfig dashboardConfig;

    /** Tenant that owns this widget; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team that owns this widget; used for per-team scoping. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** The application this widget renders data for (see {@link DashboardWidgetType} class doc). */
    @Column(name = "application_id", nullable = false)
    private Long applicationId;

    /** Which kind of data this widget renders. */
    @Enumerated(EnumType.STRING)
    @Column(name = "widget_type", nullable = false, length = 32)
    private DashboardWidgetType widgetType;

    /** Rendering order among the dashboard's widgets (0-based). */
    @Column(name = "position", nullable = false)
    private int position;

    /** Grid row (0-based, unbounded). */
    @Column(name = "grid_row", nullable = false)
    private int gridRow;

    /** Grid column (0-based, within the 4-column grid: 0..3). */
    @Column(name = "grid_column", nullable = false)
    private int gridColumn;

    /** Grid width in columns (1..4), never extending past the grid's right edge. */
    @Column(name = "grid_width", nullable = false)
    private int gridWidth;

    /** Grid height in rows (1..4). */
    @Column(name = "grid_height", nullable = false)
    private int gridHeight;

    /** Timestamp when the widget was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected DashboardWidget() {
    }

    /**
     * Full constructor for creating a new widget. {@code tenantId}/{@code teamId} are provided
     * explicitly (rather than derived from the parent dashboard) so the caller stays in control;
     * {@link DashboardService} enforces they match the owning dashboard's tenant/team.
     *
     * @param tenantId      owning tenant's {@code public.tenants.id}
     * @param teamId        owning team's {@code public.teams.id}
     * @param applicationId the target application (must already be validated by the caller)
     * @param widgetType    which kind of data this widget renders
     * @param position      rendering order (0-based)
     * @param gridRow       grid row
     * @param gridColumn    grid column (0..3, already validated by the caller)
     * @param gridWidth     grid width in columns (1..4, already validated by the caller)
     * @param gridHeight    grid height in rows (1..4, already validated by the caller)
     */
    public DashboardWidget(final Long tenantId, final Long teamId, final Long applicationId,
            final DashboardWidgetType widgetType, final int position, final int gridRow, final int gridColumn,
            final int gridWidth, final int gridHeight) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.applicationId = applicationId;
        this.widgetType = widgetType;
        this.position = position;
        this.gridRow = gridRow;
        this.gridColumn = gridColumn;
        this.gridWidth = gridWidth;
        this.gridHeight = gridHeight;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before the first
     * insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} to the current instant before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the widget's unique identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning dashboard.
     *
     * @return the {@link DashboardConfig} this widget belongs to
     */
    public DashboardConfig getDashboardConfig() {
        return dashboardConfig;
    }

    /**
     * Sets the owning dashboard (keeps both sides of the bidirectional relationship consistent,
     * cf. {@link DashboardConfig#replaceWidgets}).
     *
     * @param dashboardConfig the dashboard to attach
     */
    public void setDashboardConfig(final DashboardConfig dashboardConfig) {
        this.dashboardConfig = dashboardConfig;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the target application id.
     *
     * @return the {@code pilotage.application.id} this widget renders data for
     */
    public Long getApplicationId() {
        return applicationId;
    }

    /**
     * Returns the widget type.
     *
     * @return the {@link DashboardWidgetType}
     */
    public DashboardWidgetType getWidgetType() {
        return widgetType;
    }

    /**
     * Returns the rendering position.
     *
     * @return the 0-based position among the dashboard's widgets
     */
    public int getPosition() {
        return position;
    }

    /**
     * Returns the grid row.
     *
     * @return the grid row
     */
    public int getGridRow() {
        return gridRow;
    }

    /**
     * Returns the grid column.
     *
     * @return the grid column (0..3)
     */
    public int getGridColumn() {
        return gridColumn;
    }

    /**
     * Returns the grid width.
     *
     * @return the grid width in columns (1..4)
     */
    public int getGridWidth() {
        return gridWidth;
    }

    /**
     * Returns the grid height.
     *
     * @return the grid height in rows (1..4)
     */
    public int getGridHeight() {
        return gridHeight;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
