package fr.pivot.pilotage.schedule;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * JPA entity representing an {@code assignment} (EN22.1a, frozen contract §a) — a resource
 * assigned to a task.
 *
 * <p>{@code resourceRef} is a <strong>logical</strong> resource reference: no cross-module FK,
 * identity resolved via the PIVOT bus (ADR-006). {@code costAmount} is the planning cost internal
 * to the Gantt — a carried value, not the E26 budget aggregate.
 */
@Entity
@Table(name = "assignment", schema = "pilotage")
public class Assignment {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this assignment; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team that owns this assignment; used for per-team portfolio scoping. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Assigned task id (FK {@code pilotage.task(id)}). */
    @Column(name = "task_id", nullable = false)
    private Long taskId;

    /** Logical resource reference (no cross-module FK, resolved via the PIVOT bus). */
    @Column(name = "resource_ref", nullable = false, length = 255)
    private String resourceRef;

    /** Assignment units in percent; defaults to 100. */
    @Column(name = "units_percent", nullable = false, precision = 6, scale = 2)
    private BigDecimal unitsPercent = new BigDecimal("100");

    /** Planned work in minutes; may be {@code null}. */
    @Column(name = "work_minutes")
    private Integer workMinutes;

    /** Actual work in minutes; may be {@code null}. */
    @Column(name = "actual_work_minutes")
    private Integer actualWorkMinutes;

    /** Remaining work in minutes; may be {@code null}. */
    @Column(name = "remaining_work_minutes")
    private Integer remainingWorkMinutes;

    /** Planned cost amount (internal Gantt planning cost); may be {@code null}. */
    @Column(name = "cost_amount", precision = 18, scale = 4)
    private BigDecimal costAmount;

    /** ISO 4217 currency code; may be {@code null}. */
    @Column(name = "cost_currency", length = 3, columnDefinition = "char(3)")
    private String costCurrency;

    /** Actual cost amount; may be {@code null}. */
    @Column(name = "actual_cost_amount", precision = 18, scale = 4)
    private BigDecimal actualCostAmount;

    /** Timestamp when the assignment was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected Assignment() {
    }

    /**
     * Minimal constructor for creating a new assignment.
     *
     * @param tenantId     owning tenant's {@code public.tenants.id}
     * @param teamId       owning team's {@code public.teams.id}
     * @param taskId       assigned task id
     * @param resourceRef  logical resource reference
     * @param unitsPercent assignment units in percent
     */
    public Assignment(final Long tenantId, final Long teamId, final Long taskId, final String resourceRef,
            final BigDecimal unitsPercent) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.taskId = taskId;
        this.resourceRef = resourceRef;
        this.unitsPercent = unitsPercent;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the assignment identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the assigned task id.
     *
     * @return the task id
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * Returns the logical resource reference.
     *
     * @return the resource reference
     */
    public String getResourceRef() {
        return resourceRef;
    }

    /**
     * Sets the logical resource reference.
     *
     * @param resourceRef the resource reference to set
     */
    public void setResourceRef(final String resourceRef) {
        this.resourceRef = resourceRef;
    }

    /**
     * Returns the assignment units in percent.
     *
     * @return the units percent
     */
    public BigDecimal getUnitsPercent() {
        return unitsPercent;
    }

    /**
     * Sets the assignment units in percent.
     *
     * @param unitsPercent the units percent to set
     */
    public void setUnitsPercent(final BigDecimal unitsPercent) {
        this.unitsPercent = unitsPercent;
    }

    /**
     * Returns the planned work in minutes.
     *
     * @return the planned work, or {@code null}
     */
    public Integer getWorkMinutes() {
        return workMinutes;
    }

    /**
     * Sets the planned work in minutes.
     *
     * @param workMinutes the planned work (may be {@code null})
     */
    public void setWorkMinutes(final Integer workMinutes) {
        this.workMinutes = workMinutes;
    }

    /**
     * Returns the actual work in minutes.
     *
     * @return the actual work, or {@code null}
     */
    public Integer getActualWorkMinutes() {
        return actualWorkMinutes;
    }

    /**
     * Sets the actual work in minutes.
     *
     * @param actualWorkMinutes the actual work (may be {@code null})
     */
    public void setActualWorkMinutes(final Integer actualWorkMinutes) {
        this.actualWorkMinutes = actualWorkMinutes;
    }

    /**
     * Returns the remaining work in minutes.
     *
     * @return the remaining work, or {@code null}
     */
    public Integer getRemainingWorkMinutes() {
        return remainingWorkMinutes;
    }

    /**
     * Sets the remaining work in minutes.
     *
     * @param remainingWorkMinutes the remaining work (may be {@code null})
     */
    public void setRemainingWorkMinutes(final Integer remainingWorkMinutes) {
        this.remainingWorkMinutes = remainingWorkMinutes;
    }

    /**
     * Returns the planned cost amount.
     *
     * @return the cost amount, or {@code null}
     */
    public BigDecimal getCostAmount() {
        return costAmount;
    }

    /**
     * Sets the planned cost amount.
     *
     * @param costAmount the cost amount (may be {@code null})
     */
    public void setCostAmount(final BigDecimal costAmount) {
        this.costAmount = costAmount;
    }

    /**
     * Returns the ISO 4217 currency code.
     *
     * @return the currency code, or {@code null}
     */
    public String getCostCurrency() {
        return costCurrency;
    }

    /**
     * Sets the ISO 4217 currency code.
     *
     * @param costCurrency the currency code (may be {@code null})
     */
    public void setCostCurrency(final String costCurrency) {
        this.costCurrency = costCurrency;
    }

    /**
     * Returns the actual cost amount.
     *
     * @return the actual cost, or {@code null}
     */
    public BigDecimal getActualCostAmount() {
        return actualCostAmount;
    }

    /**
     * Sets the actual cost amount.
     *
     * @param actualCostAmount the actual cost (may be {@code null})
     */
    public void setActualCostAmount(final BigDecimal actualCostAmount) {
        this.actualCostAmount = actualCostAmount;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
