package fr.pivot.pilotage.schedule;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.time.LocalDate;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * JPA entity representing a {@code calendar_exception} (EN22.1a, frozen contract §a) — a
 * derogatory day (holiday / exceptional working day) of a {@link Calendar}.
 *
 * <p>{@code isWorking=true} marks an exceptionally worked day (optional specific working time);
 * {@code false} marks a day off. Belongs to a single tenant ({@code public.tenants.id}).
 */
@Entity
@Table(name = "calendar_exception", schema = "pilotage")
public class CalendarException {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this exception; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team that owns this exception; used for per-team portfolio scoping. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Calendar this exception belongs to (FK {@code pilotage.calendar(id)}). */
    @Column(name = "calendar_id", nullable = false)
    private Long calendarId;

    /** The derogatory day. */
    @Column(name = "exception_date", nullable = false)
    private LocalDate exceptionDate;

    /** Whether the day is worked ({@code true}) or off ({@code false}). */
    @Column(name = "is_working", nullable = false)
    private Boolean working;

    /** Specific working-time ranges as JSONB, when {@code isWorking}; may be {@code null}. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "working_time", columnDefinition = "jsonb")
    private String workingTime;

    /** Timestamp when the exception was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected CalendarException() {
    }

    /**
     * Full constructor for creating a new calendar exception.
     *
     * @param tenantId      owning tenant's {@code public.tenants.id}
     * @param teamId        owning team's {@code public.teams.id}
     * @param calendarId    parent {@code pilotage.calendar.id}
     * @param exceptionDate the derogatory day
     * @param working       {@code true} if worked, {@code false} if off
     * @param workingTime   specific working-time JSON, or {@code null}
     */
    public CalendarException(final Long tenantId, final Long teamId, final Long calendarId,
            final LocalDate exceptionDate, final Boolean working, final String workingTime) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.calendarId = calendarId;
        this.exceptionDate = exceptionDate;
        this.working = working;
        this.workingTime = workingTime;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the exception identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the parent calendar id.
     *
     * @return the {@code pilotage.calendar.id}
     */
    public Long getCalendarId() {
        return calendarId;
    }

    /**
     * Returns the derogatory day.
     *
     * @return the exception date
     */
    public LocalDate getExceptionDate() {
        return exceptionDate;
    }

    /**
     * Returns whether the day is worked.
     *
     * @return {@code true} if worked, {@code false} if off
     */
    public Boolean getWorking() {
        return working;
    }

    /**
     * Returns the specific working-time JSON.
     *
     * @return the working-time JSON, or {@code null}
     */
    public String getWorkingTime() {
        return workingTime;
    }
}
