package fr.pivot.pilotage.schedule;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity representing a working-time {@code calendar} (EN22.1a, frozen contract §a).
 *
 * <p>A calendar defines working days ({@code working_days_mask} — a Mon..Sun bitmask) and working
 * time ({@code working_time} JSONB) for a project, task or resource. A {@code null}
 * {@code projectId} means a reusable tenant/base calendar. Belongs to a single tenant
 * ({@code public.tenants.id}, owned by {@code pivot-core}). The scheduling engine (EN22.1b) reads
 * calendars to project durations onto working time — that computation is out of EN22.1a scope.
 */
@Entity
@Table(name = "calendar", schema = "pilotage")
public class Calendar {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this calendar; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Owning project id, or {@code null} for a reusable tenant/base calendar. */
    @Column(name = "project_id")
    private Long projectId;

    /** Scope the calendar applies to (project, task or resource). */
    @Enumerated(EnumType.STRING)
    @Column(name = "scope", nullable = false, length = 16)
    private CalendarScope scope;

    /** Human-readable calendar name; maximum 255 characters. */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /** Mon..Sun bitmask of working days. */
    @Column(name = "working_days_mask", nullable = false)
    private Short workingDaysMask;

    /** Working time ranges per day, stored as JSONB. */
    @Column(name = "working_time", columnDefinition = "jsonb", nullable = false)
    private String workingTime;

    /** Timestamp when the calendar was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected Calendar() {
    }

    /**
     * Full constructor for creating a new calendar.
     *
     * @param tenantId        owning tenant's {@code public.tenants.id}
     * @param projectId       owning project id, or {@code null} for a reusable calendar
     * @param scope           the scope the calendar applies to
     * @param name            calendar name (max 255 chars)
     * @param workingDaysMask Mon..Sun working-days bitmask
     * @param workingTime     working-time ranges as a JSON string
     */
    public Calendar(final Long tenantId, final Long projectId, final CalendarScope scope,
            final String name, final Short workingDaysMask, final String workingTime) {
        this.tenantId = tenantId;
        this.projectId = projectId;
        this.scope = scope;
        this.name = name;
        this.workingDaysMask = workingDaysMask;
        this.workingTime = workingTime;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the calendar identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the owning project id.
     *
     * @return the project id, or {@code null} for a reusable calendar
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * Returns the calendar scope.
     *
     * @return the {@link CalendarScope}
     */
    public CalendarScope getScope() {
        return scope;
    }

    /**
     * Returns the calendar name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the calendar name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the working-days bitmask.
     *
     * @return the Mon..Sun bitmask
     */
    public Short getWorkingDaysMask() {
        return workingDaysMask;
    }

    /**
     * Sets the working-days bitmask.
     *
     * @param workingDaysMask the Mon..Sun bitmask
     */
    public void setWorkingDaysMask(final Short workingDaysMask) {
        this.workingDaysMask = workingDaysMask;
    }

    /**
     * Returns the working-time JSON.
     *
     * @return the working-time ranges as a JSON string
     */
    public String getWorkingTime() {
        return workingTime;
    }

    /**
     * Sets the working-time JSON.
     *
     * @param workingTime the working-time ranges as a JSON string
     */
    public void setWorkingTime(final String workingTime) {
        this.workingTime = workingTime;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
