package fr.pivot.pilotage.schedule;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity representing a {@code phase} (EN22.1a, frozen contract §a) — a macro grouping,
 * optionally backed by a root summary task.
 *
 * <p>{@code parentTaskId} may point to a root summary {@link Task} ({@code null} means a plain
 * macro grouping). Belongs to a single tenant ({@code public.tenants.id}).
 */
@Entity
@Table(name = "phase", schema = "pilotage")
public class Phase {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this phase; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Owning project id (FK {@code pilotage.project(id)}). */
    @Column(name = "project_id", nullable = false)
    private Long projectId;

    /** Backing root summary task id (FK {@code pilotage.task(id)}); {@code null} if none. */
    @Column(name = "parent_task_id")
    private Long parentTaskId;

    /** Human-readable phase name; maximum 255 characters. */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /** Display order of the phase. */
    @Column(name = "position", nullable = false)
    private Integer position;

    /** Timestamp when the phase was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected Phase() {
    }

    /**
     * Full constructor for creating a new phase.
     *
     * @param tenantId     owning tenant's {@code public.tenants.id}
     * @param projectId    owning project id
     * @param parentTaskId backing root summary task id, or {@code null}
     * @param name         phase name (max 255 chars)
     * @param position     display order
     */
    public Phase(final Long tenantId, final Long projectId, final Long parentTaskId, final String name,
            final Integer position) {
        this.tenantId = tenantId;
        this.projectId = projectId;
        this.parentTaskId = parentTaskId;
        this.name = name;
        this.position = position;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the phase identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the owning project id.
     *
     * @return the project id
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * Returns the backing root summary task id.
     *
     * @return the parent task id, or {@code null}
     */
    public Long getParentTaskId() {
        return parentTaskId;
    }

    /**
     * Sets the backing root summary task id.
     *
     * @param parentTaskId the parent task id (may be {@code null})
     */
    public void setParentTaskId(final Long parentTaskId) {
        this.parentTaskId = parentTaskId;
    }

    /**
     * Returns the phase name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the phase name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the display position.
     *
     * @return the position
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * Sets the display position.
     *
     * @param position the position to set
     */
    public void setPosition(final Integer position) {
        this.position = position;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
