package fr.pivot.pilotage.schedule;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity representing a {@code task_dependency} (EN22.1a, frozen contract §a) — a directed
 * edge of the temporal graph between a predecessor and a successor task.
 *
 * <p>Schema-level constraints: {@code UNIQUE(predecessor, successor, link_type)} and
 * {@code CHECK predecessor <> successor}. Global acyclicity is validated by the engine (EN22.1b,
 * {@code SCHEDULE_CYCLE}) — not expressible in DDL and out of EN22.1a scope.
 */
@Entity
@Table(name = "task_dependency", schema = "pilotage")
public class TaskDependency {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this dependency; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team that owns this dependency; used for per-team portfolio scoping. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Predecessor task id (FK {@code pilotage.task(id)}). */
    @Column(name = "predecessor_task_id", nullable = false)
    private Long predecessorTaskId;

    /** Successor task id (FK {@code pilotage.task(id)}). */
    @Column(name = "successor_task_id", nullable = false)
    private Long successorTaskId;

    /** Link type (FS / SS / FF / SF). */
    @Enumerated(EnumType.STRING)
    @Column(name = "link_type", nullable = false, length = 2)
    private DependencyLinkType linkType;

    /** Lag ({@code >0}) or lead ({@code <0}) in worked minutes; defaults to 0. */
    @Column(name = "lag_minutes", nullable = false)
    private Integer lagMinutes = 0;

    /** Timestamp when the dependency was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected TaskDependency() {
    }

    /**
     * Full constructor for creating a new dependency.
     *
     * @param tenantId          owning tenant's {@code public.tenants.id}
     * @param teamId            owning team's {@code public.teams.id}
     * @param predecessorTaskId predecessor task id
     * @param successorTaskId   successor task id
     * @param linkType          the link type
     * @param lagMinutes        lag/lead in worked minutes
     */
    public TaskDependency(final Long tenantId, final Long teamId, final Long predecessorTaskId,
            final Long successorTaskId, final DependencyLinkType linkType, final Integer lagMinutes) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.predecessorTaskId = predecessorTaskId;
        this.successorTaskId = successorTaskId;
        this.linkType = linkType;
        this.lagMinutes = lagMinutes;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the dependency identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the predecessor task id.
     *
     * @return the predecessor task id
     */
    public Long getPredecessorTaskId() {
        return predecessorTaskId;
    }

    /**
     * Returns the successor task id.
     *
     * @return the successor task id
     */
    public Long getSuccessorTaskId() {
        return successorTaskId;
    }

    /**
     * Returns the link type.
     *
     * @return the {@link DependencyLinkType}
     */
    public DependencyLinkType getLinkType() {
        return linkType;
    }

    /**
     * Sets the link type.
     *
     * @param linkType the link type to set
     */
    public void setLinkType(final DependencyLinkType linkType) {
        this.linkType = linkType;
    }

    /**
     * Returns the lag/lead in worked minutes.
     *
     * @return the lag minutes
     */
    public Integer getLagMinutes() {
        return lagMinutes;
    }

    /**
     * Sets the lag/lead in worked minutes.
     *
     * @param lagMinutes the lag minutes to set
     */
    public void setLagMinutes(final Integer lagMinutes) {
        this.lagMinutes = lagMinutes;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
