package fr.pivot.pilotage.schedule;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

/**
 * JPA entity representing an immutable {@code task_progress_history} row (US22.4.8 security AC:
 * "l'historique des saisies est tracé (auteur, date)") — one append-only entry per progress save,
 * distinct from {@link TaskProgress}'s single current-state row (schema-level {@code UNIQUE
 * task_id}). Never updated after insert: no {@code @PreUpdate}, no setters.
 *
 * <p><strong>Author attribution (gap-era).</strong> {@link #getActorRef()} is a logical reference
 * to the caller, in the same spirit as {@link Assignment#getResourceRef()} (ADR-006) — no
 * cross-module FK to a {@code pivot-core} user, since {@code TenantContext}'s authenticated
 * principal is not yet consumable (CLAUDE.md §gap, {@code TODO-SETUP.md} §5). Replace with the
 * real principal once the starter publishes it; the column/shape does not change.
 */
@Entity
@Table(name = "task_progress_history", schema = "pilotage")
public class TaskProgressHistory {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this entry; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team that owns this entry; used for per-team portfolio scoping. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Task id (FK {@code pilotage.task(id)}) this entry was recorded against. */
    @Column(name = "task_id", nullable = false)
    private Long taskId;

    /** Logical reference to the caller who entered this value (gap-era, ADR-006). */
    @Column(name = "actor_ref", nullable = false, length = 255)
    private String actorRef;

    /** Temporal percent complete recorded by this entry. */
    @Column(name = "percent_complete", nullable = false, precision = 5, scale = 2)
    private BigDecimal percentComplete;

    /** Physical percent complete recorded by this entry; may be {@code null}. */
    @Column(name = "physical_percent_complete", precision = 5, scale = 2)
    private BigDecimal physicalPercentComplete;

    /** Actual start date recorded by this entry; may be {@code null}. */
    @Column(name = "actual_start")
    private Instant actualStart;

    /** Actual finish date recorded by this entry; may be {@code null}. */
    @Column(name = "actual_finish")
    private Instant actualFinish;

    /** Status (freshness) date recorded by this entry; may be {@code null}. */
    @Column(name = "status_date")
    private LocalDate statusDate;

    /** Timestamp this entry was recorded — the audit trail's "date". */
    @Column(name = "recorded_at", nullable = false, updatable = false)
    private Instant recordedAt;

    /** No-arg constructor required by JPA. */
    protected TaskProgressHistory() {
    }

    /**
     * Builds a new immutable history entry.
     *
     * @param tenantId                owning tenant's {@code public.tenants.id}
     * @param teamId                  owning team's {@code public.teams.id}
     * @param taskId                  the task id
     * @param actorRef                logical reference to the caller (gap-era, ADR-006)
     * @param percentComplete         the temporal percent complete recorded
     * @param physicalPercentComplete the physical percent complete recorded (may be {@code null})
     * @param actualStart             the actual start recorded (may be {@code null})
     * @param actualFinish            the actual finish recorded (may be {@code null})
     * @param statusDate              the status (freshness) date recorded (may be {@code null})
     */
    public TaskProgressHistory(final Long tenantId, final Long teamId, final Long taskId, final String actorRef,
            final BigDecimal percentComplete, final BigDecimal physicalPercentComplete, final Instant actualStart,
            final Instant actualFinish, final LocalDate statusDate) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.taskId = taskId;
        this.actorRef = actorRef;
        this.percentComplete = percentComplete;
        this.physicalPercentComplete = physicalPercentComplete;
        this.actualStart = actualStart;
        this.actualFinish = actualFinish;
        this.statusDate = statusDate;
    }

    /** Sets the recorded timestamp before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        if (this.recordedAt == null) {
            this.recordedAt = Instant.now();
        }
    }

    /**
     * Returns the entry identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the task id this entry was recorded against.
     *
     * @return the task id
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * Returns the logical reference to the caller who entered this value.
     *
     * @return the actor reference
     */
    public String getActorRef() {
        return actorRef;
    }

    /**
     * Returns the temporal percent complete recorded by this entry.
     *
     * @return the percent complete
     */
    public BigDecimal getPercentComplete() {
        return percentComplete;
    }

    /**
     * Returns the physical percent complete recorded by this entry.
     *
     * @return the physical percent complete, or {@code null}
     */
    public BigDecimal getPhysicalPercentComplete() {
        return physicalPercentComplete;
    }

    /**
     * Returns the actual start date recorded by this entry.
     *
     * @return the actual start, or {@code null}
     */
    public Instant getActualStart() {
        return actualStart;
    }

    /**
     * Returns the actual finish date recorded by this entry.
     *
     * @return the actual finish, or {@code null}
     */
    public Instant getActualFinish() {
        return actualFinish;
    }

    /**
     * Returns the status (freshness) date recorded by this entry.
     *
     * @return the status date, or {@code null}
     */
    public LocalDate getStatusDate() {
        return statusDate;
    }

    /**
     * Returns the timestamp this entry was recorded — the audit trail's "date".
     *
     * @return the recordedAt instant
     */
    public Instant getRecordedAt() {
        return recordedAt;
    }
}
