package fr.pivot.pilotage.schedule;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity representing a {@code task_constraint} (EN22.1a, frozen contract §a) — at most one
 * per task ({@code UNIQUE task_id}).
 *
 * <p>{@code constraintDate} is required for every type except {@code ASAP}/{@code ALAP} — a
 * service/engine rule (EN22.1b), not carried by the schema. {@code deadline} is a soft due date
 * that feeds variance reporting without constraining the computation.
 */
@Entity
@Table(name = "task_constraint", schema = "pilotage")
public class TaskConstraint {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this constraint; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Constrained task id (FK {@code pilotage.task(id)}, UNIQUE). */
    @Column(name = "task_id", nullable = false)
    private Long taskId;

    /** Constraint type. */
    @Enumerated(EnumType.STRING)
    @Column(name = "constraint_type", nullable = false, length = 8)
    private ConstraintType constraintType;

    /** Constraint date; required for types other than ASAP/ALAP (enforced by the service). */
    @Column(name = "constraint_date")
    private Instant constraintDate;

    /** Soft deadline; feeds variance reporting, does not constrain the computation. */
    @Column(name = "deadline")
    private Instant deadline;

    /** Timestamp when the constraint was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected TaskConstraint() {
    }

    /**
     * Full constructor for creating a new task constraint.
     *
     * @param tenantId       owning tenant's {@code public.tenants.id}
     * @param taskId         constrained task id
     * @param constraintType the constraint type
     * @param constraintDate the constraint date, or {@code null} for ASAP/ALAP
     * @param deadline       the soft deadline, or {@code null}
     */
    public TaskConstraint(final Long tenantId, final Long taskId, final ConstraintType constraintType,
            final Instant constraintDate, final Instant deadline) {
        this.tenantId = tenantId;
        this.taskId = taskId;
        this.constraintType = constraintType;
        this.constraintDate = constraintDate;
        this.deadline = deadline;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the constraint identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the constrained task id.
     *
     * @return the task id
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * Returns the constraint type.
     *
     * @return the {@link ConstraintType}
     */
    public ConstraintType getConstraintType() {
        return constraintType;
    }

    /**
     * Sets the constraint type.
     *
     * @param constraintType the constraint type to set
     */
    public void setConstraintType(final ConstraintType constraintType) {
        this.constraintType = constraintType;
    }

    /**
     * Returns the constraint date.
     *
     * @return the constraint date, or {@code null}
     */
    public Instant getConstraintDate() {
        return constraintDate;
    }

    /**
     * Sets the constraint date.
     *
     * @param constraintDate the constraint date (may be {@code null})
     */
    public void setConstraintDate(final Instant constraintDate) {
        this.constraintDate = constraintDate;
    }

    /**
     * Returns the soft deadline.
     *
     * @return the deadline, or {@code null}
     */
    public Instant getDeadline() {
        return deadline;
    }

    /**
     * Sets the soft deadline.
     *
     * @param deadline the deadline (may be {@code null})
     */
    public void setDeadline(final Instant deadline) {
        this.deadline = deadline;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
