package fr.pivot.pilotage.schedule;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

/**
 * JPA entity representing a {@code task_progress} (EN22.1a, frozen contract §a) — 1:1 with a task
 * ({@code UNIQUE task_id}).
 *
 * <p>Carries temporal completion ({@code percentComplete}), optional physical completion, actual
 * start/finish dates and this progress record's status (freshness) date.
 */
@Entity
@Table(name = "task_progress", schema = "pilotage")
public class TaskProgress {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this progress; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Task id (FK {@code pilotage.task(id)}, UNIQUE). */
    @Column(name = "task_id", nullable = false)
    private Long taskId;

    /** Temporal percent complete; defaults to 0. */
    @Column(name = "percent_complete", nullable = false, precision = 5, scale = 2)
    private BigDecimal percentComplete = BigDecimal.ZERO;

    /** Distinct physical percent complete; may be {@code null}. */
    @Column(name = "physical_percent_complete", precision = 5, scale = 2)
    private BigDecimal physicalPercentComplete;

    /** Actual start date; may be {@code null}. */
    @Column(name = "actual_start")
    private Instant actualStart;

    /** Actual finish date; may be {@code null}. */
    @Column(name = "actual_finish")
    private Instant actualFinish;

    /** Status (freshness) date of this progress record; may be {@code null}. */
    @Column(name = "status_date")
    private LocalDate statusDate;

    /** Timestamp when the progress was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected TaskProgress() {
    }

    /**
     * Minimal constructor for creating a new progress record.
     *
     * @param tenantId        owning tenant's {@code public.tenants.id}
     * @param taskId          the task id
     * @param percentComplete the temporal percent complete
     */
    public TaskProgress(final Long tenantId, final Long taskId, final BigDecimal percentComplete) {
        this.tenantId = tenantId;
        this.taskId = taskId;
        this.percentComplete = percentComplete;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the progress identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the task id.
     *
     * @return the task id
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * Returns the temporal percent complete.
     *
     * @return the percent complete
     */
    public BigDecimal getPercentComplete() {
        return percentComplete;
    }

    /**
     * Sets the temporal percent complete.
     *
     * @param percentComplete the percent complete to set
     */
    public void setPercentComplete(final BigDecimal percentComplete) {
        this.percentComplete = percentComplete;
    }

    /**
     * Returns the physical percent complete.
     *
     * @return the physical percent complete, or {@code null}
     */
    public BigDecimal getPhysicalPercentComplete() {
        return physicalPercentComplete;
    }

    /**
     * Sets the physical percent complete.
     *
     * @param physicalPercentComplete the physical percent complete (may be {@code null})
     */
    public void setPhysicalPercentComplete(final BigDecimal physicalPercentComplete) {
        this.physicalPercentComplete = physicalPercentComplete;
    }

    /**
     * Returns the actual start date.
     *
     * @return the actual start, or {@code null}
     */
    public Instant getActualStart() {
        return actualStart;
    }

    /**
     * Sets the actual start date.
     *
     * @param actualStart the actual start (may be {@code null})
     */
    public void setActualStart(final Instant actualStart) {
        this.actualStart = actualStart;
    }

    /**
     * Returns the actual finish date.
     *
     * @return the actual finish, or {@code null}
     */
    public Instant getActualFinish() {
        return actualFinish;
    }

    /**
     * Sets the actual finish date.
     *
     * @param actualFinish the actual finish (may be {@code null})
     */
    public void setActualFinish(final Instant actualFinish) {
        this.actualFinish = actualFinish;
    }

    /**
     * Returns the status (freshness) date.
     *
     * @return the status date, or {@code null}
     */
    public LocalDate getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the status (freshness) date.
     *
     * @param statusDate the status date (may be {@code null})
     */
    public void setStatusDate(final LocalDate statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
