package fr.pivot.pilotage.schedule;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.time.LocalDate;

/**
 * JPA entity representing a {@code task} — the central node of the temporal graph and the carrier
 * of the effective altitude (EN22.1a, frozen contract §a).
 *
 * <p><strong>Altitude invariant (one row = two views, ADR-010 §1):</strong> the fuzzy period
 * bounds ({@link #fuzzyPeriodStart}/{@link #fuzzyPeriodEnd}, roadmap view) and the precise dates
 * ({@link #startDate}/{@link #finishDate}, Gantt view) coexist on the same row. Which bound is
 * authoritative depends on {@link #temporalPrecision} — an application/service rule (EN22.1b), not
 * carried by the schema.
 *
 * <p><strong>Derived columns</strong> ({@link #wbsCode}, {@link #earlyStart}/{@link #earlyFinish},
 * {@link #lateStart}/{@link #lateFinish}, slack minutes, {@link #critical}): mapped here but
 * <em>never computed</em> in EN22.1a — they are populated by the scheduling engine (EN22.1b) and
 * are read-only for clients (direct writes rejected 422 at the service layer, out of EN22.1a
 * scope). They are nullable at rest.
 */
@Entity
@Table(name = "task", schema = "pilotage")
public class Task {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this task; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Team that owns this task; used for per-team portfolio scoping. */
    @Column(name = "team_id", nullable = false)
    private Long teamId;

    /** Owning project id (FK {@code pilotage.project(id)}). */
    @Column(name = "project_id", nullable = false)
    private Long projectId;

    /** Owning phase id (FK {@code pilotage.phase(id)}); {@code null} if unphased. */
    @Column(name = "phase_id")
    private Long phaseId;

    /**
     * Roadmap-rapide lane id (US22.3.1, FK {@code pilotage.lane(id)}); {@code null} for a regular
     * Gantt task never posed on a roadmap-rapide lane. Distinct from {@link #phaseId}: a lane is a
     * flat, orthogonal-to-time grouping (theme/team/objective), never adossed to a task, whereas a
     * phase is a time/WBS macro-grouping optionally backed by a root summary task.
     */
    @Column(name = "lane_id")
    private Long laneId;

    /** WBS parent task id (self-reference); {@code null} at the WBS root. */
    @Column(name = "parent_task_id")
    private Long parentTaskId;

    /**
     * WBS code — <strong>derived server-side</strong> (parent + rank), materialised for
     * sorting/virtualisation (EN22.2). Never computed in EN22.1a; nullable at rest.
     */
    @Column(name = "wbs_code", length = 64)
    private String wbsCode;

    /** Display order within the parent. */
    @Column(name = "position", nullable = false)
    private Integer position;

    /** Human-readable task name; maximum 512 characters. */
    @Column(name = "name", nullable = false, length = 512)
    private String name;

    /** Kind of node (summary / leaf / milestone / recurring). */
    @Enumerated(EnumType.STRING)
    @Column(name = "node_kind", nullable = false, length = 16)
    private NodeKind nodeKind;

    /** Whether this node is projected into the macro (roadmap) view — one object, no copy. */
    @Column(name = "shared_in_roadmap", nullable = false)
    private Boolean sharedInRoadmap;

    /**
     * Now/Next/Later bucket of a high-level (initiative) node (EN22.1c, frozen contract §c/§e);
     * {@code null} when the node is not bucketised. Drives the macro {@code buckets} projection
     * (US22.3.3); a change emits a {@code HorizonChanged} event.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "horizon", length = 8)
    private Horizon horizon;

    /** Effective altitude of the node — its temporal grain. */
    @Enumerated(EnumType.STRING)
    @Column(name = "temporal_precision", nullable = false, length = 16)
    private TemporalPrecision temporalPrecision;

    /** Lower bound of the fuzzy period (roadmap view); may be {@code null}. */
    @Column(name = "fuzzy_period_start")
    private LocalDate fuzzyPeriodStart;

    /** Upper bound of the fuzzy period (roadmap view); may be {@code null}. */
    @Column(name = "fuzzy_period_end")
    private LocalDate fuzzyPeriodEnd;

    /** Precise start date (Gantt view); may be {@code null}. */
    @Column(name = "start_date")
    private Instant startDate;

    /** Precise finish date (Gantt view); may be {@code null}. */
    @Column(name = "finish_date")
    private Instant finishDate;

    /** Duration in worked minutes (0 for a milestone); may be {@code null}. */
    @Column(name = "duration_minutes")
    private Integer durationMinutes;

    /** Early start — <strong>engine-derived</strong>; never computed in EN22.1a. */
    @Column(name = "early_start")
    private Instant earlyStart;

    /** Early finish — <strong>engine-derived</strong>; never computed in EN22.1a. */
    @Column(name = "early_finish")
    private Instant earlyFinish;

    /** Late start — <strong>engine-derived</strong>; never computed in EN22.1a. */
    @Column(name = "late_start")
    private Instant lateStart;

    /** Late finish — <strong>engine-derived</strong>; never computed in EN22.1a. */
    @Column(name = "late_finish")
    private Instant lateFinish;

    /** Total slack in minutes — <strong>engine-derived</strong>; never computed in EN22.1a. */
    @Column(name = "total_slack_minutes")
    private Integer totalSlackMinutes;

    /** Free slack in minutes — <strong>engine-derived</strong>; never computed in EN22.1a. */
    @Column(name = "free_slack_minutes")
    private Integer freeSlackMinutes;

    /** Critical-path flag — <strong>engine-derived</strong>; never computed in EN22.1a. */
    @Column(name = "is_critical")
    private Boolean critical;

    /** Task scheduling mode; {@code null} inherits the project's mode. */
    @Enumerated(EnumType.STRING)
    @Column(name = "scheduling_mode", length = 8)
    private SchedulingMode schedulingMode;

    /** Task-specific calendar id (FK {@code pilotage.calendar(id)}); {@code null} uses the project's. */
    @Column(name = "calendar_id")
    private Long calendarId;

    /** iCalendar recurrence rule; required when {@code nodeKind=RECURRING}, else {@code null}. */
    @Column(name = "recurrence_rule", columnDefinition = "text")
    private String recurrenceRule;

    /** Monotonic revision counter — optimistic co-editing lock and event ordering (EN22.2). */
    @Column(name = "revision", nullable = false)
    private Integer revision;

    /** Timestamp when the task was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected Task() {
    }

    /**
     * Minimal constructor for creating a new task with its mandatory (non-derived) fields.
     *
     * <p>Derived fields (WBS code, early/late dates, slack, critical flag) are left {@code null} —
     * they are populated by the scheduling engine (EN22.1b), never at creation.
     *
     * @param tenantId          owning tenant's {@code public.tenants.id}
     * @param teamId            owning team's {@code public.teams.id}
     * @param projectId         owning project id
     * @param position          display order within the parent
     * @param name              task name (max 512 chars)
     * @param nodeKind          kind of node
     * @param sharedInRoadmap   whether the node is projected into the roadmap view
     * @param temporalPrecision effective altitude of the node
     * @param revision          initial revision (typically 0)
     */
    public Task(final Long tenantId, final Long teamId, final Long projectId, final Integer position,
            final String name, final NodeKind nodeKind, final Boolean sharedInRoadmap,
            final TemporalPrecision temporalPrecision, final Integer revision) {
        this.tenantId = tenantId;
        this.teamId = teamId;
        this.projectId = projectId;
        this.position = position;
        this.name = name;
        this.nodeKind = nodeKind;
        this.sharedInRoadmap = sharedInRoadmap;
        this.temporalPrecision = temporalPrecision;
        this.revision = revision;
    }

    /** Sets creation/update timestamps before the first insert when unset. */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the task identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning tenant id.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the team identifier.
     *
     * @return the team's {@code public.teams.id}
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Returns the owning project id.
     *
     * @return the project id
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * Returns the owning phase id.
     *
     * @return the phase id, or {@code null} if unphased
     */
    public Long getPhaseId() {
        return phaseId;
    }

    /**
     * Sets the owning phase id.
     *
     * @param phaseId the phase id (may be {@code null})
     */
    public void setPhaseId(final Long phaseId) {
        this.phaseId = phaseId;
    }

    /**
     * Returns the WBS parent task id.
     *
     * @return the parent task id, or {@code null} at the WBS root
     */
    public Long getParentTaskId() {
        return parentTaskId;
    }

    /**
     * Sets the WBS parent task id.
     *
     * @param parentTaskId the parent task id (may be {@code null})
     */
    public void setParentTaskId(final Long parentTaskId) {
        this.parentTaskId = parentTaskId;
    }

    /**
     * Returns the roadmap-rapide lane id (US22.3.1).
     *
     * @return the lane id, or {@code null} if this task is not a roadmap-rapide initiative
     */
    public Long getLaneId() {
        return laneId;
    }

    /**
     * Sets the roadmap-rapide lane id (US22.3.1).
     *
     * @param laneId the lane id (may be {@code null})
     */
    public void setLaneId(final Long laneId) {
        this.laneId = laneId;
    }

    /**
     * Returns the server-derived WBS code (never computed in EN22.1a).
     *
     * @return the WBS code, or {@code null}
     */
    public String getWbsCode() {
        return wbsCode;
    }

    /**
     * Returns the display position within the parent.
     *
     * @return the position
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * Sets the display position within the parent.
     *
     * @param position the position to set
     */
    public void setPosition(final Integer position) {
        this.position = position;
    }

    /**
     * Returns the task name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the task name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the node kind.
     *
     * @return the {@link NodeKind}
     */
    public NodeKind getNodeKind() {
        return nodeKind;
    }

    /**
     * Sets the node kind.
     *
     * @param nodeKind the node kind to set
     */
    public void setNodeKind(final NodeKind nodeKind) {
        this.nodeKind = nodeKind;
    }

    /**
     * Returns whether the node is shared in the roadmap view.
     *
     * @return {@code true} if projected into the roadmap
     */
    public Boolean getSharedInRoadmap() {
        return sharedInRoadmap;
    }

    /**
     * Sets whether the node is shared in the roadmap view.
     *
     * @param sharedInRoadmap the flag to set
     */
    public void setSharedInRoadmap(final Boolean sharedInRoadmap) {
        this.sharedInRoadmap = sharedInRoadmap;
    }

    /**
     * Returns the Now/Next/Later horizon bucket of this node (EN22.1c).
     *
     * @return the {@link Horizon}, or {@code null} if the node is not bucketised
     */
    public Horizon getHorizon() {
        return horizon;
    }

    /**
     * Sets the Now/Next/Later horizon bucket of this node (EN22.1c).
     *
     * @param horizon the horizon to set (may be {@code null})
     */
    public void setHorizon(final Horizon horizon) {
        this.horizon = horizon;
    }

    /**
     * Returns the effective temporal precision (altitude) of the node.
     *
     * @return the {@link TemporalPrecision}
     */
    public TemporalPrecision getTemporalPrecision() {
        return temporalPrecision;
    }

    /**
     * Sets the effective temporal precision (altitude) of the node.
     *
     * @param temporalPrecision the precision to set
     */
    public void setTemporalPrecision(final TemporalPrecision temporalPrecision) {
        this.temporalPrecision = temporalPrecision;
    }

    /**
     * Returns the fuzzy period lower bound.
     *
     * @return the fuzzy period start, or {@code null}
     */
    public LocalDate getFuzzyPeriodStart() {
        return fuzzyPeriodStart;
    }

    /**
     * Sets the fuzzy period lower bound.
     *
     * @param fuzzyPeriodStart the fuzzy period start (may be {@code null})
     */
    public void setFuzzyPeriodStart(final LocalDate fuzzyPeriodStart) {
        this.fuzzyPeriodStart = fuzzyPeriodStart;
    }

    /**
     * Returns the fuzzy period upper bound.
     *
     * @return the fuzzy period end, or {@code null}
     */
    public LocalDate getFuzzyPeriodEnd() {
        return fuzzyPeriodEnd;
    }

    /**
     * Sets the fuzzy period upper bound.
     *
     * @param fuzzyPeriodEnd the fuzzy period end (may be {@code null})
     */
    public void setFuzzyPeriodEnd(final LocalDate fuzzyPeriodEnd) {
        this.fuzzyPeriodEnd = fuzzyPeriodEnd;
    }

    /**
     * Returns the precise start date.
     *
     * @return the start date, or {@code null}
     */
    public Instant getStartDate() {
        return startDate;
    }

    /**
     * Sets the precise start date.
     *
     * @param startDate the start date (may be {@code null})
     */
    public void setStartDate(final Instant startDate) {
        this.startDate = startDate;
    }

    /**
     * Returns the precise finish date.
     *
     * @return the finish date, or {@code null}
     */
    public Instant getFinishDate() {
        return finishDate;
    }

    /**
     * Sets the precise finish date.
     *
     * @param finishDate the finish date (may be {@code null})
     */
    public void setFinishDate(final Instant finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * Returns the duration in worked minutes.
     *
     * @return the duration, or {@code null}
     */
    public Integer getDurationMinutes() {
        return durationMinutes;
    }

    /**
     * Sets the duration in worked minutes.
     *
     * @param durationMinutes the duration (may be {@code null})
     */
    public void setDurationMinutes(final Integer durationMinutes) {
        this.durationMinutes = durationMinutes;
    }

    /**
     * Returns the engine-derived early start (never computed in EN22.1a).
     *
     * @return the early start, or {@code null}
     */
    public Instant getEarlyStart() {
        return earlyStart;
    }

    /**
     * Sets the engine-derived WBS code. Invoked <strong>only</strong> by the scheduling engine
     * service (EN22.1b) when persisting derived columns; client writes are refused (422) at the
     * controller layer (out of EN22.1b scope).
     *
     * @param wbsCode the derived WBS code
     */
    public void setWbsCode(final String wbsCode) {
        this.wbsCode = wbsCode;
    }

    /**
     * Sets the engine-derived early start. Engine service only (EN22.1b).
     *
     * @param earlyStart the early start
     */
    public void setEarlyStart(final Instant earlyStart) {
        this.earlyStart = earlyStart;
    }

    /**
     * Sets the engine-derived early finish. Engine service only (EN22.1b).
     *
     * @param earlyFinish the early finish
     */
    public void setEarlyFinish(final Instant earlyFinish) {
        this.earlyFinish = earlyFinish;
    }

    /**
     * Sets the engine-derived late start. Engine service only (EN22.1b).
     *
     * @param lateStart the late start
     */
    public void setLateStart(final Instant lateStart) {
        this.lateStart = lateStart;
    }

    /**
     * Sets the engine-derived late finish. Engine service only (EN22.1b).
     *
     * @param lateFinish the late finish
     */
    public void setLateFinish(final Instant lateFinish) {
        this.lateFinish = lateFinish;
    }

    /**
     * Sets the engine-derived total slack in minutes. Engine service only (EN22.1b).
     *
     * @param totalSlackMinutes the total slack
     */
    public void setTotalSlackMinutes(final Integer totalSlackMinutes) {
        this.totalSlackMinutes = totalSlackMinutes;
    }

    /**
     * Sets the engine-derived free slack in minutes. Engine service only (EN22.1b).
     *
     * @param freeSlackMinutes the free slack
     */
    public void setFreeSlackMinutes(final Integer freeSlackMinutes) {
        this.freeSlackMinutes = freeSlackMinutes;
    }

    /**
     * Sets the engine-derived critical flag. Engine service only (EN22.1b).
     *
     * @param critical the critical flag
     */
    public void setCritical(final Boolean critical) {
        this.critical = critical;
    }

    /**
     * Returns the engine-derived early finish (never computed in EN22.1a).
     *
     * @return the early finish, or {@code null}
     */
    public Instant getEarlyFinish() {
        return earlyFinish;
    }

    /**
     * Returns the engine-derived late start (never computed in EN22.1a).
     *
     * @return the late start, or {@code null}
     */
    public Instant getLateStart() {
        return lateStart;
    }

    /**
     * Returns the engine-derived late finish (never computed in EN22.1a).
     *
     * @return the late finish, or {@code null}
     */
    public Instant getLateFinish() {
        return lateFinish;
    }

    /**
     * Returns the engine-derived total slack minutes (never computed in EN22.1a).
     *
     * @return the total slack, or {@code null}
     */
    public Integer getTotalSlackMinutes() {
        return totalSlackMinutes;
    }

    /**
     * Returns the engine-derived free slack minutes (never computed in EN22.1a).
     *
     * @return the free slack, or {@code null}
     */
    public Integer getFreeSlackMinutes() {
        return freeSlackMinutes;
    }

    /**
     * Returns the engine-derived critical-path flag (never computed in EN22.1a).
     *
     * @return {@code true} if on the critical path, or {@code null} if not yet computed
     */
    public Boolean getCritical() {
        return critical;
    }

    /**
     * Returns the task scheduling mode.
     *
     * @return the {@link SchedulingMode}, or {@code null} to inherit the project's
     */
    public SchedulingMode getSchedulingMode() {
        return schedulingMode;
    }

    /**
     * Sets the task scheduling mode.
     *
     * @param schedulingMode the scheduling mode (may be {@code null})
     */
    public void setSchedulingMode(final SchedulingMode schedulingMode) {
        this.schedulingMode = schedulingMode;
    }

    /**
     * Returns the task-specific calendar id.
     *
     * @return the calendar id, or {@code null} to use the project's
     */
    public Long getCalendarId() {
        return calendarId;
    }

    /**
     * Sets the task-specific calendar id.
     *
     * @param calendarId the calendar id (may be {@code null})
     */
    public void setCalendarId(final Long calendarId) {
        this.calendarId = calendarId;
    }

    /**
     * Returns the iCalendar recurrence rule.
     *
     * @return the recurrence rule, or {@code null}
     */
    public String getRecurrenceRule() {
        return recurrenceRule;
    }

    /**
     * Sets the iCalendar recurrence rule.
     *
     * @param recurrenceRule the recurrence rule (may be {@code null})
     */
    public void setRecurrenceRule(final String recurrenceRule) {
        this.recurrenceRule = recurrenceRule;
    }

    /**
     * Returns the monotonic revision counter.
     *
     * @return the revision
     */
    public Integer getRevision() {
        return revision;
    }

    /**
     * Sets the monotonic revision counter.
     *
     * @param revision the revision to set
     */
    public void setRevision(final Integer revision) {
        this.revision = revision;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
