package fr.pivot.pilotage.project;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * JPA entity representing a pilotage {@code Application} — the root of the pilotage hierarchy
 * (EN18.1).
 *
 * <p>An application belongs to a single tenant ({@code public.tenants.id}, owned by
 * {@code pivot-core} — no local entity, cf. ADR-006/ADR-022) and aggregates zero or more
 * {@link Project} children. Timestamps are managed automatically via JPA lifecycle callbacks.
 */
@Entity
@Table(name = "application", schema = "pilotage")
public class Application {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Tenant that owns this application; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Human-readable application name; maximum 255 characters. */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /** Timestamp when the application was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Projects belonging to this application (bidirectional {@code @OneToMany}).
     *
     * <p>Mapped by {@link Project#getApplication()}; cascades persistence and orphan removal so
     * the object graph stays consistent with the database-level
     * {@code ON DELETE CASCADE} on {@code pilotage.project.application_id}.
     */
    @OneToMany(mappedBy = "application", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Project> projects = new ArrayList<>();

    /** No-arg constructor required by JPA. */
    protected Application() {
    }

    /**
     * Full constructor for creating a new application.
     *
     * @param tenantId owning tenant's {@code public.tenants.id}
     * @param name     application name (max 255 chars)
     * @param now      timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public Application(final Long tenantId, final String name, final Instant now) {
        this.tenantId = tenantId;
        this.name = name;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before the first
     * insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} to the current instant before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Adds a project to this application and sets both sides of the bidirectional relationship.
     *
     * @param project the project to attach; its {@code tenantId} is expected to match this
     *                application's tenant (enforced at the service layer in later US)
     */
    public void addProject(final Project project) {
        this.projects.add(project);
        project.setApplication(this);
    }

    /**
     * Returns the application's unique identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the application name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the application name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Returns an unmodifiable view of the projects belonging to this application.
     *
     * @return an unmodifiable list of child projects
     */
    public List<Project> getProjects() {
        return Collections.unmodifiableList(projects);
    }
}
