package fr.pivot.pilotage.project;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA entity representing a pilotage {@code Project} (EN18.1).
 *
 * <p>A project is attached to exactly one {@link Application} ({@code application_id NOT NULL} —
 * this carries the "one Project = one Application" rule) and belongs to a single tenant
 * ({@code public.tenants.id}, owned by {@code pivot-core}). The {@code tenantId} is duplicated
 * on the project (rather than only reachable through the application) to allow direct
 * tenant-scoped filtering without a systematic join. Timestamps are managed automatically via
 * JPA lifecycle callbacks.
 */
@Entity
@Table(name = "project", schema = "pilotage")
public class Project {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The single application this project belongs to; never {@code null} once persisted. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "application_id", nullable = false)
    private Application application;

    /** Tenant that owns this project; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Human-readable project name; maximum 255 characters. */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /** Timestamp when the project was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected Project() {
    }

    /**
     * Full constructor for creating a new project.
     *
     * <p>The {@code tenantId} is provided explicitly rather than derived from the application so
     * the caller stays in control of tenant assignment; the service layer (later US) enforces
     * that it matches {@code application.getTenantId()}.
     *
     * @param application the owning application (must not be {@code null})
     * @param tenantId    owning tenant's {@code public.tenants.id}
     * @param name        project name (max 255 chars)
     * @param now         timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public Project(final Application application, final Long tenantId, final String name, final Instant now) {
        this.application = application;
        this.tenantId = tenantId;
        this.name = name;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before the first
     * insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} to the current instant before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the project's unique identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning application.
     *
     * @return the {@link Application} this project belongs to
     */
    public Application getApplication() {
        return application;
    }

    /**
     * Sets the owning application (used to keep both sides of the bidirectional relationship
     * consistent, cf. {@link Application#addProject(Project)}).
     *
     * @param application the application to attach
     */
    public void setApplication(final Application application) {
        this.application = application;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the project name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the project name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
