package fr.pivot.pilotage.project;

import fr.pivot.pilotage.schedule.Calendar;
import fr.pivot.pilotage.schedule.SchedulingMode;
import fr.pivot.pilotage.schedule.TemporalPrecision;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;

import java.time.Instant;
import java.time.LocalDate;

/**
 * JPA entity representing a pilotage {@code Project} (EN18.1, extended by EN22.1a).
 *
 * <p>A project is attached to exactly one {@link Application} ({@code application_id NOT NULL} —
 * this carries the "one Project = one Application" rule) and belongs to a single tenant
 * ({@code public.tenants.id}, owned by {@code pivot-core}). The {@code tenantId} is duplicated
 * on the project (rather than only reachable through the application) to allow direct
 * tenant-scoped filtering without a systematic join. Timestamps are managed automatically via
 * JPA lifecycle callbacks.
 *
 * <p>EN22.1a adds the temporal-model anchor columns (frozen contract §a, {@code project}): the
 * default project calendar, the scheduling mode, the status (data) date and the default temporal
 * precision snapshot. The project stores no "view altitude" — that is a render preference
 * resolved via the tenant profile (EN18.10).
 */
@Entity
@Table(name = "project", schema = "pilotage")
public class Project {

    /** Primary key generated by the database via an {@code IDENTITY} column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The single application this project belongs to; never {@code null} once persisted. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "application_id", nullable = false)
    private Application application;

    /** Tenant that owns this project; used for multi-tenant isolation. */
    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** Human-readable project name; maximum 255 characters. */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /**
     * Default project calendar (EN22.1a); may be {@code null} until a calendar is assigned.
     *
     * <p>FK to {@code pilotage.calendar(id)}. Loaded lazily; the temporal graph and the
     * scheduling engine (EN22.1b) read working days/times through it.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "calendar_id")
    private Calendar calendar;

    /**
     * Project scheduling mode (EN22.1a); defaults to {@link SchedulingMode#AUTO}. A task may
     * override it; a task with a {@code null} mode inherits this value.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "scheduling_mode", nullable = false, length = 8)
    private SchedulingMode schedulingMode = SchedulingMode.AUTO;

    /**
     * Status (data) date (EN22.1a) — freshness guard against a "lying Gantt" (ADR-010); the
     * source of truth for the project. {@code null} until first set.
     */
    @Column(name = "status_date")
    private LocalDate statusDate;

    /**
     * Default temporal precision (EN22.1a): a snapshot of {@code resolveProfile(tenant).altitude}
     * taken at creation. {@code null} means the profile must be re-read on the fly (EN18.10).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "default_temporal_precision", length = 16)
    private TemporalPrecision defaultTemporalPrecision;

    /** Timestamp when the project was first persisted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Timestamp of the last update; refreshed automatically before every update. */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** No-arg constructor required by JPA. */
    protected Project() {
    }

    /**
     * Full constructor for creating a new project.
     *
     * <p>The {@code tenantId} is provided explicitly rather than derived from the application so
     * the caller stays in control of tenant assignment; the service layer (later US) enforces
     * that it matches {@code application.getTenantId()}.
     *
     * @param application the owning application (must not be {@code null})
     * @param tenantId    owning tenant's {@code public.tenants.id}
     * @param name        project name (max 255 chars)
     * @param now         timestamp used for both {@code createdAt} and {@code updatedAt}
     */
    public Project(final Application application, final Long tenantId, final String name, final Instant now) {
        this.application = application;
        this.tenantId = tenantId;
        this.name = name;
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Sets {@code createdAt} and {@code updatedAt} to the current instant before the first
     * insert, when the fields have not already been set.
     */
    @PrePersist
    public void prePersist() {
        final Instant now = Instant.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
    }

    /** Refreshes {@code updatedAt} to the current instant before every update. */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns the project's unique identifier.
     *
     * @return the id, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the owning application.
     *
     * @return the {@link Application} this project belongs to
     */
    public Application getApplication() {
        return application;
    }

    /**
     * Sets the owning application (used to keep both sides of the bidirectional relationship
     * consistent, cf. {@link Application#addProject(Project)}).
     *
     * @param application the application to attach
     */
    public void setApplication(final Application application) {
        this.application = application;
    }

    /**
     * Returns the tenant identifier.
     *
     * @return the tenant's {@code public.tenants.id}
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the project name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the project name.
     *
     * @param name the name to set
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the default project calendar (EN22.1a).
     *
     * @return the {@link Calendar}, or {@code null} if none is assigned
     */
    public Calendar getCalendar() {
        return calendar;
    }

    /**
     * Sets the default project calendar (EN22.1a).
     *
     * @param calendar the calendar to assign (may be {@code null})
     */
    public void setCalendar(final Calendar calendar) {
        this.calendar = calendar;
    }

    /**
     * Returns the project scheduling mode (EN22.1a).
     *
     * @return the {@link SchedulingMode} (never {@code null}, defaults to {@code AUTO})
     */
    public SchedulingMode getSchedulingMode() {
        return schedulingMode;
    }

    /**
     * Sets the project scheduling mode (EN22.1a).
     *
     * @param schedulingMode the scheduling mode to set
     */
    public void setSchedulingMode(final SchedulingMode schedulingMode) {
        this.schedulingMode = schedulingMode;
    }

    /**
     * Returns the status (data) date (EN22.1a).
     *
     * @return the status date, or {@code null} if never set
     */
    public LocalDate getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the status (data) date (EN22.1a).
     *
     * @param statusDate the status date to set (may be {@code null})
     */
    public void setStatusDate(final LocalDate statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * Returns the default temporal precision snapshot (EN22.1a).
     *
     * @return the {@link TemporalPrecision}, or {@code null} to re-read the profile on the fly
     */
    public TemporalPrecision getDefaultTemporalPrecision() {
        return defaultTemporalPrecision;
    }

    /**
     * Sets the default temporal precision snapshot (EN22.1a).
     *
     * @param defaultTemporalPrecision the temporal precision to set (may be {@code null})
     */
    public void setDefaultTemporalPrecision(final TemporalPrecision defaultTemporalPrecision) {
        this.defaultTemporalPrecision = defaultTemporalPrecision;
    }

    /**
     * Returns the creation timestamp.
     *
     * @return the createdAt instant
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last-updated timestamp.
     *
     * @return the updatedAt instant
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
